// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ImportLesson(arg1) {
  return window['go']['main']['App']['ImportLesson'](arg1);
}

export function ImportRoadmap(arg1) {
  return window['go']['main']['App']['ImportRoadmap'](arg1);
}

export function ListLessons() {
  return window['go']['main']['App']['ListLessons']();
}

export function ListRoadmaps() {
  return window['go']['main']['App']['ListRoadmaps']();
}

export function LoadRoadmap(arg1) {
  return window['go']['main']['App']['LoadRoadmap'](arg1);
}

export function ResetLesson(arg1) {
  return window['go']['main']['App']['ResetLesson'](arg1);
}

export function RunChecks(arg1) {
  return window['go']['main']['App']['RunChecks'](arg1);
}

export function SelectAndImportLesson() {
  return window['go']['main']['App']['SelectAndImportLesson']();
}

export function SelectAndImportRoadmap() {
  return window['go']['main']['App']['SelectAndImportRoadmap']();
}

export function StartLesson(arg1) {
  return window['go']['main']['App']['StartLesson'](arg1);
}

export function StartRoadmapLesson(arg1, arg2) {
  return window['go']['main']['App']['StartRoadmapLesson'](arg1, arg2);
}

export function StopLesson(arg1) {
  return window['go']['main']['App']['StopLesson'](arg1);
}

export function TerminalInput(arg1, arg2) {
  return window['go']['main']['App']['TerminalInput'](arg1, arg2);
}

export function TerminalResize(arg1, arg2, arg3) {
  return window['go']['main']['App']['TerminalResize'](arg1, arg2, arg3);
}
