// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {lessons} from '../models';
import {roadmaps} from '../models';
import {main} from '../models';
import {checks} from '../models';

export function ImportLesson(arg1:string):Promise<lessons.Summary>;

export function ImportRoadmap(arg1:string):Promise<roadmaps.Summary>;

export function ListLessons():Promise<Array<lessons.Summary>>;

export function ListRoadmaps():Promise<Array<roadmaps.Summary>>;

export function LoadRoadmap(arg1:string):Promise<roadmaps.Roadmap>;

export function ResetLesson(arg1:string):Promise<main.LessonSessionState>;

export function RunChecks(arg1:string):Promise<Array<checks.Result>>;

export function SelectAndImportLesson():Promise<lessons.Summary>;

export function SelectAndImportRoadmap():Promise<roadmaps.Summary>;

export function StartLesson(arg1:string):Promise<main.LessonSessionState>;

export function StartRoadmapLesson(arg1:string,arg2:string):Promise<main.LessonSessionState>;

export function StopLesson(arg1:string):Promise<void>;

export function TerminalInput(arg1:string,arg2:string):Promise<void>;

export function TerminalResize(arg1:string,arg2:number,arg3:number):Promise<void>;
